"""Assemble one runnable SPICE deck from includes, main netlist, and board overlay.

Contract (fixed order — do not reorder without updating tests and this docstring):

1. Each path in ``assembly.includes`` (in list order), as ``.include`` directives.
2. ``assembly.main``.
3. Mandatory overlay at ``<config-dir>/sim/overlay.cir``.

The generated deck is written to ``<config-dir>/sim/assembled.cir`` (overwritten each run).
All ``.include`` paths in the generated file are relative to ``sim/`` (the output file's directory)
so ngspice resolves them consistently.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class AssemblySpec:
    """Paths are relative to the directory containing ``sim.yml`` (board root)."""

    main_rel: str
    includes_rel: tuple[str, ...]


OVERLAY_REL = Path("sim") / "overlay.cir"
ASSEMBLED_REL = Path("sim") / "assembled.cir"


def _include_line(target_resolved: Path, output_dir_resolved: Path) -> str:
    rel = Path(
        os.path.relpath(str(target_resolved.resolve()), str(output_dir_resolved.resolve())),
    )
    quoted = rel.as_posix()
    return f'.include "{quoted}"'


def write_assembled_deck(config_dir: Path, spec: AssemblySpec, output_path: Path) -> None:
    """Write ``output_path`` by merging includes, main, and overlay per contract order."""
    cfg = config_dir.resolve()
    out = output_path.resolve()
    out_dir = out.parent
    out_dir.mkdir(parents=True, exist_ok=True)

    main_path = (cfg / spec.main_rel).resolve()
    overlay_path = (cfg / OVERLAY_REL).resolve()

    if not main_path.is_file():
        raise ValueError(f"assembly main netlist not found: {main_path}")
    if not overlay_path.is_file():
        raise ValueError(f"overlay stub missing (required): {overlay_path}")

    include_paths: list[Path] = []
    for raw in spec.includes_rel:
        p = (cfg / raw).resolve()
        if not p.is_file():
            raise ValueError(f"assembly include not found: {p}")
        include_paths.append(p)

    lines: list[str] = [
        "* Assembled SPICE deck — generated by scripts/sim/assemble.py — DO NOT EDIT",
        "* Include order: includes[] (in order) → main → sim/overlay.cir",
        "",
    ]
    for inc in include_paths:
        lines.append(_include_line(inc, out_dir))
    lines.append(_include_line(main_path, out_dir))
    lines.append(_include_line(overlay_path, out_dir))
    lines.append("")

    out.write_text("\n".join(lines))
