M48
; DRILL file KiCad 10.0.1-10.0.1~ubuntu25.10.1 date 2026-05-29T00:15:12
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-29T00:15:12+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1-10.0.1~ubuntu25.10.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X116.887Y-111.377
X116.887Y-117.157
M30
